import { Inter } from 'next/font/google'

import "./globals.css";
import { ThemeProvider } from "@/components/Theme/ThemeProvider";
import { Navbar } from "@/components/Navbar/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col h-screen">
            <Navbar />
            <main className="flex-1 overflow-y-hidden">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
